package boards

import "minmax.uk/autopal/pkg/life"

func Blinker() *life.GameState {
	return life.MustFromString(5, 5, `
		.....
		..#..
		..#..
		..#..
		.....
`)
}
func Block() *life.GameState {
	return life.MustFromString(4, 4, `
		....
		.##.
		.##.
		....
`)
}
func Beehive() *life.GameState {
	return life.MustFromString(6, 5, `
		......
		..##..
		.#..#.
		..##..
		......
`)
}

func Toad() *life.GameState {
	return life.MustFromString(6, 6, `
		......
		...#..
		.#..#.
		.#..#.
		..#...
		......
`)
}

func Pulsar() *life.GameState {
	return life.MustFromString(17, 17, `
		.................
		.................
		....OOO...OOO....
		.................
		..O....O.O....O..
		..O....O.O....O..
		..O....O.O....O..
		....OOO...OOO....
		.................
		....OOO...OOO....
		..O....O.O....O..
		..O....O.O....O..
		..O....O.O....O..
		.................
		....OOO...OOO....
		.................
		.................
`)
}
