// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/life/life.proto

package proto_life

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed int64 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Rows int64 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols int64 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
}

func (x *GetRandomStateRequest) Reset() {
	*x = GetRandomStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_life_life_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomStateRequest) ProtoMessage() {}

func (x *GetRandomStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_life_life_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomStateRequest.ProtoReflect.Descriptor instead.
func (*GetRandomStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_life_life_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomStateRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *GetRandomStateRequest) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *GetRandomStateRequest) GetCols() int64 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type GetRandomStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *GameState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *GetRandomStateResponse) Reset() {
	*x = GetRandomStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_life_life_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomStateResponse) ProtoMessage() {}

func (x *GetRandomStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_life_life_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomStateResponse.ProtoReflect.Descriptor instead.
func (*GetRandomStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_life_life_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomStateResponse) GetState() *GameState {
	if x != nil {
		return x.State
	}
	return nil
}

type GetNextStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentState *GameState `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
}

func (x *GetNextStateRequest) Reset() {
	*x = GetNextStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_life_life_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNextStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextStateRequest) ProtoMessage() {}

func (x *GetNextStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_life_life_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextStateRequest.ProtoReflect.Descriptor instead.
func (*GetNextStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_life_life_proto_rawDescGZIP(), []int{2}
}

func (x *GetNextStateRequest) GetCurrentState() *GameState {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

type GetNextStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewState *GameState `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
}

func (x *GetNextStateResponse) Reset() {
	*x = GetNextStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_life_life_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNextStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextStateResponse) ProtoMessage() {}

func (x *GetNextStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_life_life_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextStateResponse.ProtoReflect.Descriptor instead.
func (*GetNextStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_life_life_proto_rawDescGZIP(), []int{3}
}

func (x *GetNextStateResponse) GetNewState() *GameState {
	if x != nil {
		return x.NewState
	}
	return nil
}

type PlayRandomGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed            int64 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Rows            int64 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols            int64 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Iterations      int64 `protobuf:"varint,4,opt,name=iterations,proto3" json:"iterations,omitempty"`
	UntilStabilizes bool  `protobuf:"varint,5,opt,name=until_stabilizes,json=untilStabilizes,proto3" json:"until_stabilizes,omitempty"`
}

func (x *PlayRandomGameRequest) Reset() {
	*x = PlayRandomGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_life_life_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRandomGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRandomGameRequest) ProtoMessage() {}

func (x *PlayRandomGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_life_life_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRandomGameRequest.ProtoReflect.Descriptor instead.
func (*PlayRandomGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_life_life_proto_rawDescGZIP(), []int{4}
}

func (x *PlayRandomGameRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *PlayRandomGameRequest) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PlayRandomGameRequest) GetCols() int64 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PlayRandomGameRequest) GetIterations() int64 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *PlayRandomGameRequest) GetUntilStabilizes() bool {
	if x != nil {
		return x.UntilStabilizes
	}
	return false
}

type PlayRandomGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iteration int64      `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	State     *GameState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *PlayRandomGameResponse) Reset() {
	*x = PlayRandomGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_life_life_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRandomGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRandomGameResponse) ProtoMessage() {}

func (x *PlayRandomGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_life_life_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRandomGameResponse.ProtoReflect.Descriptor instead.
func (*PlayRandomGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_life_life_proto_rawDescGZIP(), []int{5}
}

func (x *PlayRandomGameResponse) GetIteration() int64 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *PlayRandomGameResponse) GetState() *GameState {
	if x != nil {
		return x.State
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows  int64  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols  int64  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Cells []bool `protobuf:"varint,3,rep,packed,name=cells,proto3" json:"cells,omitempty"` // shoule have length of rows * cols
}

func (x *GameState) Reset() {
	*x = GameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_life_life_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_life_life_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_life_life_proto_rawDescGZIP(), []int{6}
}

func (x *GameState) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *GameState) GetCols() int64 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *GameState) GetCells() []bool {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_proto_life_life_proto protoreflect.FileDescriptor

var file_proto_life_life_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x66, 0x65, 0x2f, 0x6c, 0x69, 0x66,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c,
	0x2e, 0x6c, 0x69, 0x66, 0x65, 0x22, 0x53, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x65,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x22, 0x47, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69,
	0x66, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69, 0x66, 0x65,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x4c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x78, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69,
	0x66, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x65,
	0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x10,
	0x75, 0x6e, 0x74, 0x69, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x7a, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x53, 0x74, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x7a, 0x65, 0x73, 0x22, 0x65, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x79, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x49,
	0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x08, 0x52, 0x05, 0x63, 0x65, 0x6c, 0x6c, 0x73, 0x32, 0xa6, 0x02, 0x0a, 0x0b, 0x4c, 0x69,
	0x66, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x61, 0x75,
	0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69, 0x66, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x78, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70,
	0x61, 0x6c, 0x2e, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x75,
	0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65,
	0x78, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x5f, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2e, 0x6c, 0x69,
	0x66, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x70,
	0x61, 0x6c, 0x2e, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x1e, 0x5a, 0x1c, 0x6d, 0x69, 0x6e, 0x6d, 0x61, 0x78, 0x2e, 0x75, 0x6b, 0x2f,
	0x61, 0x75, 0x74, 0x6f, 0x70, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69,
	0x66, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_life_life_proto_rawDescOnce sync.Once
	file_proto_life_life_proto_rawDescData = file_proto_life_life_proto_rawDesc
)

func file_proto_life_life_proto_rawDescGZIP() []byte {
	file_proto_life_life_proto_rawDescOnce.Do(func() {
		file_proto_life_life_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_life_life_proto_rawDescData)
	})
	return file_proto_life_life_proto_rawDescData
}

var file_proto_life_life_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_life_life_proto_goTypes = []interface{}{
	(*GetRandomStateRequest)(nil),  // 0: autopal.life.GetRandomStateRequest
	(*GetRandomStateResponse)(nil), // 1: autopal.life.GetRandomStateResponse
	(*GetNextStateRequest)(nil),    // 2: autopal.life.GetNextStateRequest
	(*GetNextStateResponse)(nil),   // 3: autopal.life.GetNextStateResponse
	(*PlayRandomGameRequest)(nil),  // 4: autopal.life.PlayRandomGameRequest
	(*PlayRandomGameResponse)(nil), // 5: autopal.life.PlayRandomGameResponse
	(*GameState)(nil),              // 6: autopal.life.GameState
}
var file_proto_life_life_proto_depIdxs = []int32{
	6, // 0: autopal.life.GetRandomStateResponse.state:type_name -> autopal.life.GameState
	6, // 1: autopal.life.GetNextStateRequest.current_state:type_name -> autopal.life.GameState
	6, // 2: autopal.life.GetNextStateResponse.new_state:type_name -> autopal.life.GameState
	6, // 3: autopal.life.PlayRandomGameResponse.state:type_name -> autopal.life.GameState
	0, // 4: autopal.life.LifeService.GetRandomState:input_type -> autopal.life.GetRandomStateRequest
	2, // 5: autopal.life.LifeService.GetNextState:input_type -> autopal.life.GetNextStateRequest
	4, // 6: autopal.life.LifeService.PlayRandomGame:input_type -> autopal.life.PlayRandomGameRequest
	1, // 7: autopal.life.LifeService.GetRandomState:output_type -> autopal.life.GetRandomStateResponse
	3, // 8: autopal.life.LifeService.GetNextState:output_type -> autopal.life.GetNextStateResponse
	5, // 9: autopal.life.LifeService.PlayRandomGame:output_type -> autopal.life.PlayRandomGameResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_life_life_proto_init() }
func file_proto_life_life_proto_init() {
	if File_proto_life_life_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_life_life_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_life_life_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_life_life_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNextStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_life_life_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNextStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_life_life_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRandomGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_life_life_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRandomGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_life_life_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_life_life_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_life_life_proto_goTypes,
		DependencyIndexes: file_proto_life_life_proto_depIdxs,
		MessageInfos:      file_proto_life_life_proto_msgTypes,
	}.Build()
	File_proto_life_life_proto = out.File
	file_proto_life_life_proto_rawDesc = nil
	file_proto_life_life_proto_goTypes = nil
	file_proto_life_life_proto_depIdxs = nil
}
